{{- if and .Values.fhirFileServer.enabled .Values.fhirFileServer.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rs-api-server
  labels:
    app: rs-api-server
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: rs-api-server
  minReplicas: {{ .Values.fhirFileServer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.fhirFileServer.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.fhirFileServer.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.fhirFileServer.autoscaling.targetCPU }}
    {{- end }}
    {{- if .Values.fhirFileServer.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.fhirFileServer.autoscaling.targetMemory  }}
    {{- end }}
{{- end }}
