ingress:
  hostname: hostname
  annotations: {
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # use letsencrypt-prod if proper letsencrypt certs are required
  }

nodeSelector: 
  node.kubernetes.io/instance-type: t3a.large
resources:
  limits:
    cpu: 1800m
    memory: 3800Mi
  requests:
    cpu: 1400m
    memory: 3Gi
persistence:
  storageClass: "ebs-csi-storage-class"
  size: 30Gi

