spring:
  datasource:
    url: 'jdbc:postgresql://psql-postgresql-ha-pgpool.postgres.svc.cluster.local:5432/icmr_rs'
    username: icmr_rs_user
    password: 
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: true