apiVersion: apps/v1
kind: Deployment
metadata:
  name: osticket-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osticket-mysql
  template:
    metadata:
      labels:
        app: osticket-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: osticket-config
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: osticket-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: osticket-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: osticket-config
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: osticket-db-data
---
apiVersion: v1
kind: Service
metadata:
  name: osticket-mysql
spec:
  selector:
    app: osticket-mysql
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None 