apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osticket-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osticket-uploads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osticket-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 