apiVersion: batch/v1
kind: Job
metadata:
  name: osticket-config-init-job
  namespace: os-ticket
spec:
  template:
    spec:
      containers:
      - name: config-init
        image: ghcr.io/datakaveri/os-ticket:1.0.2
        command: ['sh', '-c']
        args:
        - |
          echo "Checking if config already exists..."
          if [ -f "/config-storage/ost-config.php" ]; then
            echo "Config file already exists, skipping initialization"
            exit 0
          fi
          
          echo "Creating initial config file from sample..."
          cp /var/www/html/include/ost-sampleconfig.php /config-storage/ost-config.php
          chmod 666 /config-storage/ost-config.php
          
          echo "Config file created successfully!"
          echo "First few lines of config file:"
          head -10 /config-storage/ost-config.php
        volumeMounts:
        - name: config-volume
          mountPath: /config-storage
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: osticket-config
      restartPolicy: Never
  backoffLimit: 3