apiVersion: apps/v1
kind: Deployment
metadata:
  name: osticket-web
  namespace: os-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osticket-web
  template:
    metadata:
      labels:
        app: osticket-web
    spec:
      nodeSelector:
         beta.kubernetes.io/instance-type: t3a.large
      containers:
      - name: osticket
        image: <enter imaage URL here>
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_HOST
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        volumeMounts:
        - name: uploads
          mountPath: /var/www/html/upload
        - name: uploads
          mountPath: /var/www/html/upload/ost-config.php
          subPath: ost-config.php
        # - name: data
        #   mountPath: /var/www/html/data
        resources:
          limits:
            cpu: 1400m
            memory: 1.5Gi
          requests:
            cpu: 1000m
            memory: 1.0Gi
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: osticket-uploads
      # - name: config
      #   persistentVolumeClaim:
      #     claimName: osticket-config
      # - name: data
      #   persistentVolumeClaim:
      #     claimName: osticket-data
---
apiVersion: v1
kind: Service
metadata:
  name: osticket-web
  namespace: os-ticket
spec:
  selector:
    app: osticket-web
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
