ingress:
  hostname: fhir-onboarding.iudx.io
  annotations: {
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # use letsencrypt-prod if proper letsencrypt certs are required
  }
  
## fhirOnboardingServer resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
## @param fhirOnboardingServer.resources.limits The resources limits for the fhirOnboardingServer containers
## @param fhirOnboardingServer.resources.requests The requested resources for the fhirOnboardingServer containers
##
fhirOnboardingServer:
  nodeSelector:
    node.kubernetes.io/instance-type: t3a.large
  resources:
    limits:
      cpu: 1000m
      memory: 1200Mi
    requests: 
      cpu: 700m
      memory: 1200Mi
  persistence:
    storageClass: "ebs-csi-storage-class"

